image: Visual Studio 2019

version: '{build}'

clone_depth: 50

environment:
  TEST_SECRET:
    secure: y6fntBCP/dHsbo4YqrNYRu3dwqF6JoipEEU8s6qK0K3gEUyIkMYgMgYznGF05HfrHWRHyZtTj/Wup0jW4KgX/ay54+UfvVZ9PScUW7CpvOw=
  matrix:
    - platform: x86
      JAVA_HOME: ${ProgramFiles(x86)}\Java\jdk1.8.0
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk1.8.0
      VT_API_KEY:
        secure: 3sqJDjLAS708tR/LiAqKLZTnLLrhGJuWVzzI4nCjLbUUsZB+PPRG3y0BWWnMo14CDhBT4v6yjHTA23RdopoHDWJlBcGhKELKZOLhHsnJLU8=

build_script:
  - cmd: mvn clean verify -B -V -e -ntp

after_build:
  - cmd: IF "%APPVEYOR_REPO_TAG%" == "true" IF DEFINED VT_API_KEY SET ARTIFACTS_PATH=target\*.* & FOR /R target %%f IN (*.exe *.tar.gz *.zip) DO IF NOT %%~xf == .exec ECHO Submitting file "%%f" to VirusTotal... & curl -v -F "file=@%%f" -F apikey=%VT_API_KEY% https://www.virustotal.com/vtapi/v2/file/scan & ECHO File "%%f" submitted to VirusTotal. & TIMEOUT 15 /NOBREAK

artifacts:
  - path: $(ARTIFACTS_PATH)
    type: file

deploy:
  description: 'Autogenerated'
  provider: GitHub
  auth_token:
    secure: iraKgcF8ghXlZsLu+cIcsqqxeNTyeuCkLCtXA+SkOKrVFyGp+djEDD0ga3O8AHRb
  draft: true
  on:
    appveyor_repo_tag: true
