environment:
  JRE6_HOME: $(ProgramFiles)\Java\jdk1.6.0\jre

  matrix:
    - JAVA_HOME: $(ProgramFiles)\Java\jdk1.6.0
    - JAVA_HOME: $(ProgramFiles)\Java\jdk1.7.0
    - JAVA_HOME: $(ProgramFiles)\Java\jdk1.8.0

install:
  - ps: $env:ANT_VERSION = '1.9.8'
  - ps: if (!(Test-Path -Path ($env:ChocolateyInstall + '\lib\ant\apache-ant-' + $env:ANT_VERSION))) { cinst ant -i --version $env:ANT_VERSION }
  - cmd: PATH %ChocolateyInstall%\lib\ant\apache-ant-%ANT_VERSION%\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: java -Xmx32m -version
  - cmd: javac -J-Xmx32m -version
  - cmd: ant -version

cache:
  - $(ChocolateyInstall)\lib\ant

platform:
  - x86
  - x64

build_script:
  - ant all

after_build:
  - ps: If ($env:APPVEYOR_REPO_TAG -eq 'true') { $env:ARTIFACTS_PATH = 'target\release\*.*' }

artifacts:
  - path: $(ARTIFACTS_PATH)
    type: file
