language: java
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
  - os: linux
    jdk: oraclejdk7
  - os: linux
    jdk: openjdk7
  - os: linux
    jdk: openjdk6
  - os: osx
addons:
  sonarcloud:
    organization: albertus82-github
  apt:
    sources:
    - sourceline: ppa:ubuntu-wine/ppa
    packages:
    - wine1.7
    - lib32z1
    - lib32ncurses5
env:
  global:
  - secure: CfCsUAsJP0ffKmGchWunlNTYfp+3bAGBrvabCI+smeqKwzNFabKMoQlkTErv7k9uBVbv21ZMEySeWpFFQaNU697vFV2dDhygl1whNnLZY9LgZ/vGSBfi8dJt/tNdsy5ep8O24kWpNbs93Kg29qvBlTpCTgvNzinBGUhyTkzZj//By/tgo9dS9RIDjRTG3u/JGQkhGvLMwj4Wr8IKoZD/D91aNfrxhc0EkM85kRHYX799zoKjDaP08HYaC/d6uNi7wMviZwyLe9IuKdHVY6JIQgqLscZwoM9C5fn5ke+d5FodDxXNYCcadMrxJLGT0/JbB7WERFE36onJhPClfH646C625eTSgWyfeogjkEobeeOd/jSYjqkqzkDUuy8BW73Sdhe1PWPwloEOgqx0DEHvLaaYGk6yLAvO7vdPm0mkHwnsHEZDVzbcQBcJW8BFzTv//EP/IgA1m8PPUei7UrYriCJ2ww/bBnk7SVSBw9ZenU4GhT2huYvVdAVDMZNWJcD5Ub8rGiky3N+irN2RoEJwYGEZByo8TJHO3aGciZMn/Huag7vlq1NN41VBYjCLUN+k1/mB9q7041TM8fPPCldC0TV0Gexw67en+YDYG+xB6i4WKqS+ZbOXb79yJGLUvD0h4FXiCzyNpEgPfhq6+pEvrRs5oy78zi1tfj7W37Y+miQ=
  - JRE6_HOME=/usr/lib/jvm/java-6-openjdk-amd64/jre
  matrix:
    secure: DHO68zodaXDnmxziXNMtAg98xk6i/Io4QLtV9hKZtGsLtHEQMRxUN6iHY0j5EciMuFpKWPEsgqzmRnthwux+z88pSYv1Ep0a5Hii7WMCvuNWoCsTMOn+98illABL5ZfkesKKoMksU1Tkf7nDFtswc1tmXIf0msP0EVudKL/fmnPK8TgxhnY6KloK0joDzODl4M3+Zr6QaPtVk+PRifvEogqTeDhY0KdwjJGfHTx275Y3fJO3xsXORffzuPP+CFDL7nYLHBw9WkrZiXwjNDwmPpwBuhtrFJqhUcoOYm8Y2MYu+fwbmlDHEaO7kLgg/yDtJaWpkAMjeb2S49hOdxwH11Gu/YYQFA8dlEaLwO3W9KjFSU3FeVffPwfvHpsTu7sCZ0XrtxsUwzcVjXkylDg8CfYHaGEK+3ytasdfsaYpxowMq6UDg1lVquqBskODD5Iioc4UIyYzi5VxftiFuo4kAEcyI/pCDOJLpouA6HvBOdbTS8oxEp6mnNMkjljBmQgzb6Q/3AiHyEp7DOVh5Ds6OKN+wkJ85Tzr7HNyM4zbKxS/u3HPMFn1K2SKoevXCAVOtfrhS1EAS15iQw6HSvgtXnOe7nd+ONLNULn2BojwJu4XPAK43PXdFT5CQsE0nV5qLYvWVmlJyV+4K/lmSjCt2XGa2wXWZWHkKLMokYOWtwE=
before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install wine ant; fi;
script:
- ant all
- if [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then sonar-scanner -Dsonar.login=$SONAR_TOKEN;
  fi;
