language: java
script: ant all
env: JRE6_HOME=/usr/lib/jvm/java-6-openjdk-amd64/jre
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
sudo: required
before_script:
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo apt-get update -qq
  - sudo apt-get -y --force-yes install lib32z1 lib32ncurses5 wine1.7
