name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        java: [ '8', '9', '10', '11' ]
        os: [ 'windows-latest', 'ubuntu-latest', 'macOS-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - if: startsWith(matrix.os, 'ubuntu')
      run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install -y wine32
    - if: startsWith(matrix.os, 'macOS')
      run: brew update && brew install ant wine
    - uses: actions/setup-java@master
      with:
        java-version: ${{ matrix.java }}
    - run: ant -diagnostics
    - run: ant -noinput
    - if: matrix.os == 'ubuntu-latest' && matrix.java == '11'
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_SCANNER_OPTS: -Dsonar.organization=albertus82-github
        JAVA_HOME: '' # Avoid 'java: not found' error
