name: Build

on: push

jobs:
  build:
    name: Build
    strategy:
      matrix:
        java: [ '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19-ea' ]
        os: [ windows-latest, ubuntu-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_OPTS: -Dhttp.keepAlive=false
    steps:
    - uses: actions/checkout@v3
    - uses: albertus82/setup-java@main
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - run: ./mvnw clean verify -B -V -e -ntp
