name: Sonar

on: push

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dhttp.keepAlive=false
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=albertus82-github -B -V -e -ntp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
